#!/usr/bin/env python3
"""Reproducible validation harness for the PomPom bootstrap.

The timeout below is only a host-process safety limit.  It is never encoded in
PomPom and is not normalization fuel; semantic acceptance still comes solely
from the closed proof generated by KeiBootstrap.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import re
import subprocess
import sys
import tempfile
import time
from dataclasses import asdict, dataclass
from pathlib import Path


SUCCESS_MARKER = "Kei checked your file with successful"
EXPECTED_PARSE_REJECTIONS = {"casting", "test2"}


@dataclass(frozen=True)
class Case:
    suite: str
    module: str
    name: str
    entrypoint: Path
    expected: str
    bridge_classification: str
    selection: tuple[str, ...]


@dataclass
class Result:
    suite: str
    module: str
    name: str
    expected: str
    status: str
    seconds: float
    harness_bytes: int
    log: str
    harness: str
    detail: str

    @property
    def passed(self) -> bool:
        return self.status == "PASS"


def command_output(arguments: list[str], cwd: Path) -> str:
    completed = subprocess.run(
        arguments,
        cwd=cwd,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    return completed.stdout.strip()


def executable_paths(root: Path, build: bool) -> tuple[Path, Path]:
    if build:
        subprocess.run(["cabal", "build", "all"], cwd=root, check=True)
    checker = Path(command_output(["cabal", "list-bin", "exe:Kei2"], root))
    bridge = Path(command_output(["cabal", "list-bin", "exe:KeiBootstrap"], root))
    return checker, bridge


def library_cases(root: Path, selected: set[str]) -> list[Case]:
    cases: list[Case] = []
    for source in sorted((root / "libs").glob("*.pom")):
        if selected and source.stem not in selected:
            continue
        expected = "reject" if source.stem in EXPECTED_PARSE_REJECTIONS else "accept"
        classification = "parse-error" if source.stem in EXPECTED_PARSE_REJECTIONS else "parsed"
        cases.append(Case("libs", source.stem, source.stem, source.with_suffix("").relative_to(root), expected, classification, ("current",)))
    return cases


def fuzzy_cases(root: Path, selected: set[str]) -> list[Case]:
    directory = root / "boostrap" / "fuzzy_false"
    cases: list[Case] = []
    if not directory.exists():
        return cases
    for source in sorted(directory.glob("*.pom")):
        if selected and source.stem not in selected:
            continue
        if source.stem == "malformed_source":
            classification = "parse-error"
        elif source.stem == "repeated_pattern_binder":
            classification = "repeated-pattern-binder"
        else:
            classification = "parsed"
        cases.append(Case("fuzzy", source.stem, source.stem, source.with_suffix("").relative_to(root), "reject", classification, ("current",)))
    return cases


def safe_name(case: Case) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]", "-", f"{case.suite}-{case.name}")


def current_declaration_count(root: Path, bridge: Path, artifacts: Path, case: Case) -> int:
    probe = artifacts / f".{safe_name(case)}-count.pom"
    completed = subprocess.run(
        [str(bridge), str(case.entrypoint), str(probe), case.expected, "current", "0", "0"],
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    marker = "Bootstrap bridge classification: parsed"
    if completed.returncode != 0 or marker not in completed.stdout:
        raise RuntimeError(f"cannot discover declaration count for {case.entrypoint}:\n{completed.stdout}")
    match = re.search(r"^Bootstrap current declarations: ([0-9]+)$", completed.stdout, re.MULTILINE)
    if match is None:
        raise RuntimeError(f"bridge omitted declaration count for {case.entrypoint}:\n{completed.stdout}")
    return int(match.group(1))


def shard_library_cases(
    root: Path,
    bridge: Path,
    artifacts: Path,
    cases: list[Case],
    shard_size: int,
) -> list[Case]:
    if shard_size == 0:
        return cases
    sharded: list[Case] = []
    for case in cases:
        if case.suite != "libs" or case.expected != "accept":
            sharded.append(case)
            continue
        count = current_declaration_count(root, bridge, artifacts, case)
        if count == 0:
            sharded.append(case)
            continue
        for offset in range(0, count, shard_size):
            limit = min(shard_size, count - offset)
            sharded.append(
                Case(
                    case.suite,
                    case.module,
                    f"{case.module}__{offset:04d}_{offset + limit:04d}",
                    case.entrypoint,
                    case.expected,
                    case.bridge_classification,
                    ("current", str(offset), str(limit)),
                )
            )
    return sharded


def run_case(
    root: Path,
    bridge: Path,
    checker: Path,
    artifacts: Path,
    timeout_seconds: float,
    case: Case,
) -> Result:
    base = artifacts / safe_name(case)
    harness = base.with_suffix(".pom")
    log = base.with_suffix(".log")
    start = time.monotonic()
    bridge_arguments = [
        str(bridge),
        str(case.entrypoint),
        str(harness),
        case.expected,
        *case.selection,
    ]
    generated = subprocess.run(
        bridge_arguments,
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    if generated.returncode != 0:
        log.write_text(generated.stdout, encoding="utf-8")
        return Result(
            case.suite,
            case.module,
            case.name,
            case.expected,
            "BRIDGE_ERROR",
            time.monotonic() - start,
            harness.stat().st_size if harness.exists() else 0,
            str(log),
            str(harness),
            f"bridge exited {generated.returncode}",
        )

    classification_marker = f"Bootstrap bridge classification: {case.bridge_classification}"
    if classification_marker not in generated.stdout:
        log.write_text(generated.stdout, encoding="utf-8")
        return Result(
            case.suite,
            case.module,
            case.name,
            case.expected,
            "BRIDGE_CLASSIFICATION_ERROR",
            time.monotonic() - start,
            harness.stat().st_size if harness.exists() else 0,
            str(log),
            str(harness),
            f"expected bridge classification {case.bridge_classification!r}",
        )

    try:
        checked = subprocess.run(
            [str(checker), str(harness.with_suffix(""))],
            cwd=root,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout_seconds,
        )
        output = generated.stdout + checked.stdout
        log.write_text(output, encoding="utf-8")
        if SUCCESS_MARKER in checked.stdout:
            status = "PASS"
            detail = "closed bootstrap proof accepted"
        else:
            status = "CHECK_ERROR"
            detail = f"checker exited {checked.returncode} without the success marker"
    except subprocess.TimeoutExpired as problem:
        partial = problem.stdout or ""
        if isinstance(partial, bytes):
            partial = partial.decode("utf-8", errors="replace")
        log.write_text(generated.stdout + partial, encoding="utf-8")
        status = "TIMEOUT"
        detail = f"host safety timeout after {timeout_seconds:g}s"

    return Result(
        case.suite,
        case.module,
        case.name,
        case.expected,
        status,
        time.monotonic() - start,
        harness.stat().st_size if harness.exists() else 0,
        str(log),
        str(harness),
        detail,
    )


def run_internal(root: Path, checker: Path, artifacts: Path, timeout_seconds: float) -> Result:
    log = artifacts / "internal-bootstrap.log"
    start = time.monotonic()
    try:
        checked = subprocess.run(
            [str(checker), "boostrap/driver"],
            cwd=root,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout_seconds,
        )
        log.write_text(checked.stdout, encoding="utf-8")
        status = "PASS" if SUCCESS_MARKER in checked.stdout else "CHECK_ERROR"
        detail = "all imported internal proofs accepted" if status == "PASS" else "internal proof entrypoint lacked success marker"
    except subprocess.TimeoutExpired as problem:
        partial = problem.stdout or ""
        if isinstance(partial, bytes):
            partial = partial.decode("utf-8", errors="replace")
        log.write_text(partial, encoding="utf-8")
        status = "TIMEOUT"
        detail = f"host safety timeout after {timeout_seconds:g}s"
    return Result("internal", "driver", "driver", "accept", status, time.monotonic() - start, 0, str(log), "", detail)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--suite", choices=("all", "internal", "libs", "fuzzy"), default="all")
    parser.add_argument("--case", action="append", default=[], help="restrict libs/fuzzy cases by basename; repeatable")
    parser.add_argument("--jobs", type=int, default=2)
    parser.add_argument("--shard-size", type=int, default=4, help="accepted library declarations per proof harness; 0 disables sharding")
    parser.add_argument("--timeout", type=float, default=1200.0, help="host safety timeout per checker process")
    parser.add_argument("--artifacts", type=Path, help="directory for generated proof harnesses, logs, and summary.json")
    parser.add_argument("--no-build", action="store_true")
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    if arguments.jobs < 1:
        raise SystemExit("--jobs must be positive")
    if arguments.timeout <= 0:
        raise SystemExit("--timeout must be positive")
    if arguments.shard_size < 0:
        raise SystemExit("--shard-size must be non-negative")

    root = Path(__file__).resolve().parent.parent
    selected = set(arguments.case)
    temporary: tempfile.TemporaryDirectory[str] | None = None
    if arguments.artifacts is None:
        temporary = tempfile.TemporaryDirectory(prefix="pompom-bootstrap-")
        artifacts = Path(temporary.name)
    else:
        artifacts = arguments.artifacts.resolve()
        artifacts.mkdir(parents=True, exist_ok=True)

    checker, bridge = executable_paths(root, not arguments.no_build)
    results: list[Result] = []
    if arguments.suite in {"all", "internal"}:
        result = run_internal(root, checker, artifacts, arguments.timeout)
        results.append(result)
        print(f"{result.status:12} internal/driver {result.seconds:8.2f}s", flush=True)

    cases: list[Case] = []
    if arguments.suite in {"all", "libs"}:
        cases.extend(shard_library_cases(root, bridge, artifacts, library_cases(root, selected), arguments.shard_size))
    if arguments.suite in {"all", "fuzzy"}:
        cases.extend(fuzzy_cases(root, selected))

    with concurrent.futures.ThreadPoolExecutor(max_workers=arguments.jobs) as executor:
        pending = {
            executor.submit(run_case, root, bridge, checker, artifacts, arguments.timeout, case): case
            for case in cases
        }
        for future in concurrent.futures.as_completed(pending):
            result = future.result()
            results.append(result)
            print(
                f"{result.status:12} {result.suite}/{result.name:24} "
                f"{result.seconds:8.2f}s {result.harness_bytes:9d} bytes",
                flush=True,
            )

    results.sort(key=lambda result: (result.suite, result.name))
    module_status: dict[str, bool] = {}
    for result in results:
        key = f"{result.suite}/{result.module}"
        module_status[key] = module_status.get(key, True) and result.passed
    summary = {
        "success_marker": SUCCESS_MARKER,
        "timeout_is_host_safety_only": True,
        "passed": sum(result.passed for result in results),
        "total": len(results),
        "modules": module_status,
        "results": [asdict(result) for result in results],
    }
    summary_path = artifacts / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(f"summary: {summary_path}")
    success = bool(results) and all(result.passed for result in results)
    if temporary is not None and not success:
        print("temporary artifacts were retained only for this process; rerun with --artifacts to preserve them", file=sys.stderr)
    return 0 if success else 1


if __name__ == "__main__":
    raise SystemExit(main())
