(* Annotation erasure; generated by annotated/generate_syntax.py. *)
Require Export annotated.ASyntax.
Require nameless.DBSyntax.
Module Raw := nameless.DBSyntax.

Fixpoint erase (t : term) : Raw.term :=
  match t with
  | TVar n => Raw.TVar n
  | TSort k => Raw.TSort k
  | TPi A B => Raw.TPi (erase A) (erase B)
  | TLam A B b => Raw.TLam (erase b)
  | TApp A B f a => Raw.TApp (erase f) (erase a)
  | TSigma A B => Raw.TSigma (erase A) (erase B)
  | TPair A B a b => Raw.TPair (erase a) (erase b)
  | TFst A B p => Raw.TFst (erase p)
  | TSnd A B p => Raw.TSnd (erase p)
  | TUnitT => Raw.TUnitT
  | TUnit => Raw.TUnit
  | TUId => Raw.TUId
  | TTag s => Raw.TTag s
  | TEnumU => Raw.TEnumU
  | TNilE => Raw.TNilE
  | TConsE tag E => Raw.TConsE (erase tag) (erase E)
  | TEnumT E => Raw.TEnumT (erase E)
  | TEZero tag E => Raw.TEZero
  | TESucc tag E n => Raw.TESucc (erase n)
  | TEPi k E P => Raw.TEPi k (erase E) (erase P)
  | TSwitch k E P p e => Raw.TSwitch k (erase E) (erase P) (erase p) (erase e)
  | TIDesc IT => Raw.TIDesc (erase IT)
  | TIVar IT i => Raw.TIVar (erase i)
  | TI1 IT => Raw.TI1
  | TIBot IT => Raw.TIBot
  | TIProd IT A B => Raw.TIProd (erase A) (erase B)
  | TIPi IT A D => Raw.TIPi (erase A) (erase D)
  | TISig IT A D => Raw.TISig (erase A) (erase D)
  | TIChoice IT E D => Raw.TIChoice (erase E) (erase D)
  | TInterp IT D X => Raw.TInterp (erase IT) (erase D) (erase X)
  | TMuI IT D => Raw.TMuI (erase IT) (erase D)
  | TInMu IT D i x => Raw.TIn (erase x)
  | TInClose IT F G i x => Raw.TIn (erase x)
  | TInd IT D P s i x => Raw.TInd (erase IT) (erase D) (erase P) (erase s) (erase i) (erase x)
  | TIAll IT D X x P => Raw.TIAll (erase IT) (erase D) (erase X) (erase x) (erase P)
  | THyps IT D X P h x => Raw.THyps (erase IT) (erase D) (erase X) (erase P) (erase h) (erase x)
  | TClose IT F G => Raw.TClose (erase IT) (erase F) (erase G)
  | TCloseCase k IT F G i Q b x => Raw.TCloseCase k (erase IT) (erase F) (erase G) (erase i) (erase Q) (erase b) (erase x)
  | TCloseInd IT G P s F i x => Raw.TCloseInd (erase IT) (erase G) (erase P) (erase s) (erase F) (erase i) (erase x)
  end.
