(* Annotated open-signature core, under construction.
   Generated by annotated/generate_syntax.py; proofs are separate.
   All hidden introduction/elimination types are retained as terms.
   Binding and eta freshness include these annotations. *)
From Stdlib Require Import List Arith String.
Import ListNotations.

Inductive term : Type :=
| TVar (n : nat)
| TSort (k : nat)
| TPi (A : term) (B : term)
| TLam (A : term) (B : term) (b : term)
| TApp (A : term) (B : term) (f : term) (a : term)
| TSigma (A : term) (B : term)
| TPair (A : term) (B : term) (a : term) (b : term)
| TFst (A : term) (B : term) (p : term)
| TSnd (A : term) (B : term) (p : term)
| TUnitT
| TUnit
| TUId
| TTag (s : string)
| TEnumU
| TNilE
| TConsE (tag : term) (E : term)
| TEnumT (E : term)
| TEZero (tag : term) (E : term)
| TESucc (tag : term) (E : term) (n : term)
| TEPi (k : nat) (E : term) (P : term)
| TSwitch (k : nat) (E : term) (P : term) (p : term) (e : term)
| TIDesc (IT : term)
| TIVar (IT : term) (i : term)
| TI1 (IT : term)
| TIBot (IT : term)
| TIProd (IT : term) (A : term) (B : term)
| TIPi (IT : term) (A : term) (D : term)
| TISig (IT : term) (A : term) (D : term)
| TIChoice (IT : term) (E : term) (D : term)
| TInterp (IT : term) (D : term) (X : term)
| TMuI (IT : term) (D : term)
| TInMu (IT : term) (D : term) (i : term) (x : term)
| TInClose (IT : term) (F : term) (G : term) (i : term) (x : term)
| TInd (IT : term) (D : term) (P : term) (s : term) (i : term) (x : term)
| TIAll (IT : term) (D : term) (X : term) (x : term) (P : term)
| THyps (IT : term) (D : term) (X : term) (P : term) (h : term) (x : term)
| TClose (IT : term) (F : term) (G : term)
| TCloseCase (k : nat) (IT : term) (F : term) (G : term) (i : term) (Q : term) (b : term) (x : term)
| TCloseInd (IT : term) (G : term) (P : term) (s : term) (F : term) (i : term) (x : term).

Fixpoint lift (d c : nat) (t : term) : term :=
  match t with
  | TVar n => if n <? c then TVar n else TVar (d + n)
  | TSort k => TSort k
  | TPi A B => TPi (lift d c A) (lift d (S c) B)
  | TLam A B b => TLam (lift d c A) (lift d (S c) B) (lift d (S c) b)
  | TApp A B f a => TApp (lift d c A) (lift d (S c) B) (lift d c f) (lift d c a)
  | TSigma A B => TSigma (lift d c A) (lift d (S c) B)
  | TPair A B a b => TPair (lift d c A) (lift d (S c) B) (lift d c a) (lift d c b)
  | TFst A B p => TFst (lift d c A) (lift d (S c) B) (lift d c p)
  | TSnd A B p => TSnd (lift d c A) (lift d (S c) B) (lift d c p)
  | TUnitT => TUnitT
  | TUnit => TUnit
  | TUId => TUId
  | TTag s => TTag s
  | TEnumU => TEnumU
  | TNilE => TNilE
  | TConsE tag E => TConsE (lift d c tag) (lift d c E)
  | TEnumT E => TEnumT (lift d c E)
  | TEZero tag E => TEZero (lift d c tag) (lift d c E)
  | TESucc tag E n => TESucc (lift d c tag) (lift d c E) (lift d c n)
  | TEPi k E P => TEPi k (lift d c E) (lift d c P)
  | TSwitch k E P p e => TSwitch k (lift d c E) (lift d c P) (lift d c p) (lift d c e)
  | TIDesc IT => TIDesc (lift d c IT)
  | TIVar IT i => TIVar (lift d c IT) (lift d c i)
  | TI1 IT => TI1 (lift d c IT)
  | TIBot IT => TIBot (lift d c IT)
  | TIProd IT A B => TIProd (lift d c IT) (lift d c A) (lift d c B)
  | TIPi IT A D => TIPi (lift d c IT) (lift d c A) (lift d c D)
  | TISig IT A D => TISig (lift d c IT) (lift d c A) (lift d c D)
  | TIChoice IT E D => TIChoice (lift d c IT) (lift d c E) (lift d c D)
  | TInterp IT D X => TInterp (lift d c IT) (lift d c D) (lift d c X)
  | TMuI IT D => TMuI (lift d c IT) (lift d c D)
  | TInMu IT D i x => TInMu (lift d c IT) (lift d c D) (lift d c i) (lift d c x)
  | TInClose IT F G i x => TInClose (lift d c IT) (lift d c F) (lift d c G) (lift d c i) (lift d c x)
  | TInd IT D P s i x => TInd (lift d c IT) (lift d c D) (lift d c P) (lift d c s) (lift d c i) (lift d c x)
  | TIAll IT D X x P => TIAll (lift d c IT) (lift d c D) (lift d c X) (lift d c x) (lift d c P)
  | THyps IT D X P h x => THyps (lift d c IT) (lift d c D) (lift d c X) (lift d c P) (lift d c h) (lift d c x)
  | TClose IT F G => TClose (lift d c IT) (lift d c F) (lift d c G)
  | TCloseCase k IT F G i Q b x => TCloseCase k (lift d c IT) (lift d c F) (lift d c G) (lift d c i) (lift d c Q) (lift d c b) (lift d c x)
  | TCloseInd IT G P s F i x => TCloseInd (lift d c IT) (lift d c G) (lift d c P) (lift d c s) (lift d c F) (lift d c i) (lift d c x)
  end.

Fixpoint subst (u : term) (c : nat) (t : term) : term :=
  match t with
  | TVar n => if n <? c then TVar n else if n =? c then lift c 0 u else TVar (Nat.pred n)
  | TSort k => TSort k
  | TPi A B => TPi (subst u c A) (subst u (S c) B)
  | TLam A B b => TLam (subst u c A) (subst u (S c) B) (subst u (S c) b)
  | TApp A B f a => TApp (subst u c A) (subst u (S c) B) (subst u c f) (subst u c a)
  | TSigma A B => TSigma (subst u c A) (subst u (S c) B)
  | TPair A B a b => TPair (subst u c A) (subst u (S c) B) (subst u c a) (subst u c b)
  | TFst A B p => TFst (subst u c A) (subst u (S c) B) (subst u c p)
  | TSnd A B p => TSnd (subst u c A) (subst u (S c) B) (subst u c p)
  | TUnitT => TUnitT
  | TUnit => TUnit
  | TUId => TUId
  | TTag s => TTag s
  | TEnumU => TEnumU
  | TNilE => TNilE
  | TConsE tag E => TConsE (subst u c tag) (subst u c E)
  | TEnumT E => TEnumT (subst u c E)
  | TEZero tag E => TEZero (subst u c tag) (subst u c E)
  | TESucc tag E n => TESucc (subst u c tag) (subst u c E) (subst u c n)
  | TEPi k E P => TEPi k (subst u c E) (subst u c P)
  | TSwitch k E P p e => TSwitch k (subst u c E) (subst u c P) (subst u c p) (subst u c e)
  | TIDesc IT => TIDesc (subst u c IT)
  | TIVar IT i => TIVar (subst u c IT) (subst u c i)
  | TI1 IT => TI1 (subst u c IT)
  | TIBot IT => TIBot (subst u c IT)
  | TIProd IT A B => TIProd (subst u c IT) (subst u c A) (subst u c B)
  | TIPi IT A D => TIPi (subst u c IT) (subst u c A) (subst u c D)
  | TISig IT A D => TISig (subst u c IT) (subst u c A) (subst u c D)
  | TIChoice IT E D => TIChoice (subst u c IT) (subst u c E) (subst u c D)
  | TInterp IT D X => TInterp (subst u c IT) (subst u c D) (subst u c X)
  | TMuI IT D => TMuI (subst u c IT) (subst u c D)
  | TInMu IT D i x => TInMu (subst u c IT) (subst u c D) (subst u c i) (subst u c x)
  | TInClose IT F G i x => TInClose (subst u c IT) (subst u c F) (subst u c G) (subst u c i) (subst u c x)
  | TInd IT D P s i x => TInd (subst u c IT) (subst u c D) (subst u c P) (subst u c s) (subst u c i) (subst u c x)
  | TIAll IT D X x P => TIAll (subst u c IT) (subst u c D) (subst u c X) (subst u c x) (subst u c P)
  | THyps IT D X P h x => THyps (subst u c IT) (subst u c D) (subst u c X) (subst u c P) (subst u c h) (subst u c x)
  | TClose IT F G => TClose (subst u c IT) (subst u c F) (subst u c G)
  | TCloseCase k IT F G i Q b x => TCloseCase k (subst u c IT) (subst u c F) (subst u c G) (subst u c i) (subst u c Q) (subst u c b) (subst u c x)
  | TCloseInd IT G P s F i x => TCloseInd (subst u c IT) (subst u c G) (subst u c P) (subst u c s) (subst u c F) (subst u c i) (subst u c x)
  end.

Fixpoint occurs (c : nat) (t : term) : bool :=
  match t with
  | TVar n => n =? c
  | TSort k => false
  | TPi A B => occurs c A || occurs (S c) B
  | TLam A B b => occurs c A || occurs (S c) B || occurs (S c) b
  | TApp A B f a => occurs c A || occurs (S c) B || occurs c f || occurs c a
  | TSigma A B => occurs c A || occurs (S c) B
  | TPair A B a b => occurs c A || occurs (S c) B || occurs c a || occurs c b
  | TFst A B p => occurs c A || occurs (S c) B || occurs c p
  | TSnd A B p => occurs c A || occurs (S c) B || occurs c p
  | TUnitT => false
  | TUnit => false
  | TUId => false
  | TTag s => false
  | TEnumU => false
  | TNilE => false
  | TConsE tag E => occurs c tag || occurs c E
  | TEnumT E => occurs c E
  | TEZero tag E => occurs c tag || occurs c E
  | TESucc tag E n => occurs c tag || occurs c E || occurs c n
  | TEPi k E P => occurs c E || occurs c P
  | TSwitch k E P p e => occurs c E || occurs c P || occurs c p || occurs c e
  | TIDesc IT => occurs c IT
  | TIVar IT i => occurs c IT || occurs c i
  | TI1 IT => occurs c IT
  | TIBot IT => occurs c IT
  | TIProd IT A B => occurs c IT || occurs c A || occurs c B
  | TIPi IT A D => occurs c IT || occurs c A || occurs c D
  | TISig IT A D => occurs c IT || occurs c A || occurs c D
  | TIChoice IT E D => occurs c IT || occurs c E || occurs c D
  | TInterp IT D X => occurs c IT || occurs c D || occurs c X
  | TMuI IT D => occurs c IT || occurs c D
  | TInMu IT D i x => occurs c IT || occurs c D || occurs c i || occurs c x
  | TInClose IT F G i x => occurs c IT || occurs c F || occurs c G || occurs c i || occurs c x
  | TInd IT D P s i x => occurs c IT || occurs c D || occurs c P || occurs c s || occurs c i || occurs c x
  | TIAll IT D X x P => occurs c IT || occurs c D || occurs c X || occurs c x || occurs c P
  | THyps IT D X P h x => occurs c IT || occurs c D || occurs c X || occurs c P || occurs c h || occurs c x
  | TClose IT F G => occurs c IT || occurs c F || occurs c G
  | TCloseCase k IT F G i Q b x => occurs c IT || occurs c F || occurs c G || occurs c i || occurs c Q || occurs c b || occurs c x
  | TCloseInd IT G P s F i x => occurs c IT || occurs c G || occurs c P || occurs c s || occurs c F || occurs c i || occurs c x
  end.

Fixpoint tsize (t : term) : nat :=
  match t with
  | TVar n => 1
  | TSort k => 1
  | TPi A B => S (tsize A + tsize B)
  | TLam A B b => S (tsize A + tsize B + tsize b)
  | TApp A B f a => S (tsize A + tsize B + tsize f + tsize a)
  | TSigma A B => S (tsize A + tsize B)
  | TPair A B a b => S (tsize A + tsize B + tsize a + tsize b)
  | TFst A B p => S (tsize A + tsize B + tsize p)
  | TSnd A B p => S (tsize A + tsize B + tsize p)
  | TUnitT => 1
  | TUnit => 1
  | TUId => 1
  | TTag s => 1
  | TEnumU => 1
  | TNilE => 1
  | TConsE tag E => S (tsize tag + tsize E)
  | TEnumT E => S (tsize E)
  | TEZero tag E => S (tsize tag + tsize E)
  | TESucc tag E n => S (tsize tag + tsize E + tsize n)
  | TEPi k E P => S (tsize E + tsize P)
  | TSwitch k E P p e => S (tsize E + tsize P + tsize p + tsize e)
  | TIDesc IT => S (tsize IT)
  | TIVar IT i => S (tsize IT + tsize i)
  | TI1 IT => S (tsize IT)
  | TIBot IT => S (tsize IT)
  | TIProd IT A B => S (tsize IT + tsize A + tsize B)
  | TIPi IT A D => S (tsize IT + tsize A + tsize D)
  | TISig IT A D => S (tsize IT + tsize A + tsize D)
  | TIChoice IT E D => S (tsize IT + tsize E + tsize D)
  | TInterp IT D X => S (tsize IT + tsize D + tsize X)
  | TMuI IT D => S (tsize IT + tsize D)
  | TInMu IT D i x => S (tsize IT + tsize D + tsize i + tsize x)
  | TInClose IT F G i x => S (tsize IT + tsize F + tsize G + tsize i + tsize x)
  | TInd IT D P s i x => S (tsize IT + tsize D + tsize P + tsize s + tsize i + tsize x)
  | TIAll IT D X x P => S (tsize IT + tsize D + tsize X + tsize x + tsize P)
  | THyps IT D X P h x => S (tsize IT + tsize D + tsize X + tsize P + tsize h + tsize x)
  | TClose IT F G => S (tsize IT + tsize F + tsize G)
  | TCloseCase k IT F G i Q b x => S (tsize IT + tsize F + tsize G + tsize i + tsize Q + tsize b + tsize x)
  | TCloseInd IT G P s F i x => S (tsize IT + tsize G + tsize P + tsize s + tsize F + tsize i + tsize x)
  end.

Definition ctx := list term.
Definition arrow A B := TPi A (lift 1 0 B).
Definition product A B := TSigma A (lift 1 0 B).
Definition Def IT := TPi IT (TIDesc (lift 1 0 IT)).
Definition Family IT := TPi IT (TSort 0).
Definition Bot := TEnumT TNilE.

Inductive compatible (R : term -> term -> Prop) : term -> term -> Prop :=
| cp_TPi_A : forall A B A',
    R A A' -> compatible R (TPi A B) (TPi A' B)
| cp_TPi_B : forall A B B',
    R B B' -> compatible R (TPi A B) (TPi A B')
| cp_TLam_A : forall A B b A',
    R A A' -> compatible R (TLam A B b) (TLam A' B b)
| cp_TLam_B : forall A B b B',
    R B B' -> compatible R (TLam A B b) (TLam A B' b)
| cp_TLam_b : forall A B b b',
    R b b' -> compatible R (TLam A B b) (TLam A B b')
| cp_TApp_A : forall A B f a A',
    R A A' -> compatible R (TApp A B f a) (TApp A' B f a)
| cp_TApp_B : forall A B f a B',
    R B B' -> compatible R (TApp A B f a) (TApp A B' f a)
| cp_TApp_f : forall A B f a f',
    R f f' -> compatible R (TApp A B f a) (TApp A B f' a)
| cp_TApp_a : forall A B f a a',
    R a a' -> compatible R (TApp A B f a) (TApp A B f a')
| cp_TSigma_A : forall A B A',
    R A A' -> compatible R (TSigma A B) (TSigma A' B)
| cp_TSigma_B : forall A B B',
    R B B' -> compatible R (TSigma A B) (TSigma A B')
| cp_TPair_A : forall A B a b A',
    R A A' -> compatible R (TPair A B a b) (TPair A' B a b)
| cp_TPair_B : forall A B a b B',
    R B B' -> compatible R (TPair A B a b) (TPair A B' a b)
| cp_TPair_a : forall A B a b a',
    R a a' -> compatible R (TPair A B a b) (TPair A B a' b)
| cp_TPair_b : forall A B a b b',
    R b b' -> compatible R (TPair A B a b) (TPair A B a b')
| cp_TFst_A : forall A B p A',
    R A A' -> compatible R (TFst A B p) (TFst A' B p)
| cp_TFst_B : forall A B p B',
    R B B' -> compatible R (TFst A B p) (TFst A B' p)
| cp_TFst_p : forall A B p p',
    R p p' -> compatible R (TFst A B p) (TFst A B p')
| cp_TSnd_A : forall A B p A',
    R A A' -> compatible R (TSnd A B p) (TSnd A' B p)
| cp_TSnd_B : forall A B p B',
    R B B' -> compatible R (TSnd A B p) (TSnd A B' p)
| cp_TSnd_p : forall A B p p',
    R p p' -> compatible R (TSnd A B p) (TSnd A B p')
| cp_TConsE_tag : forall tag E tag',
    R tag tag' -> compatible R (TConsE tag E) (TConsE tag' E)
| cp_TConsE_E : forall tag E E',
    R E E' -> compatible R (TConsE tag E) (TConsE tag E')
| cp_TEnumT_E : forall E E',
    R E E' -> compatible R (TEnumT E) (TEnumT E')
| cp_TEZero_tag : forall tag E tag',
    R tag tag' -> compatible R (TEZero tag E) (TEZero tag' E)
| cp_TEZero_E : forall tag E E',
    R E E' -> compatible R (TEZero tag E) (TEZero tag E')
| cp_TESucc_tag : forall tag E n tag',
    R tag tag' -> compatible R (TESucc tag E n) (TESucc tag' E n)
| cp_TESucc_E : forall tag E n E',
    R E E' -> compatible R (TESucc tag E n) (TESucc tag E' n)
| cp_TESucc_n : forall tag E n n',
    R n n' -> compatible R (TESucc tag E n) (TESucc tag E n')
| cp_TEPi_E : forall k E P E',
    R E E' -> compatible R (TEPi k E P) (TEPi k E' P)
| cp_TEPi_P : forall k E P P',
    R P P' -> compatible R (TEPi k E P) (TEPi k E P')
| cp_TSwitch_E : forall k E P p e E',
    R E E' -> compatible R (TSwitch k E P p e) (TSwitch k E' P p e)
| cp_TSwitch_P : forall k E P p e P',
    R P P' -> compatible R (TSwitch k E P p e) (TSwitch k E P' p e)
| cp_TSwitch_p : forall k E P p e p',
    R p p' -> compatible R (TSwitch k E P p e) (TSwitch k E P p' e)
| cp_TSwitch_e : forall k E P p e e',
    R e e' -> compatible R (TSwitch k E P p e) (TSwitch k E P p e')
| cp_TIDesc_IT : forall IT IT',
    R IT IT' -> compatible R (TIDesc IT) (TIDesc IT')
| cp_TIVar_IT : forall IT i IT',
    R IT IT' -> compatible R (TIVar IT i) (TIVar IT' i)
| cp_TIVar_i : forall IT i i',
    R i i' -> compatible R (TIVar IT i) (TIVar IT i')
| cp_TI1_IT : forall IT IT',
    R IT IT' -> compatible R (TI1 IT) (TI1 IT')
| cp_TIBot_IT : forall IT IT',
    R IT IT' -> compatible R (TIBot IT) (TIBot IT')
| cp_TIProd_IT : forall IT A B IT',
    R IT IT' -> compatible R (TIProd IT A B) (TIProd IT' A B)
| cp_TIProd_A : forall IT A B A',
    R A A' -> compatible R (TIProd IT A B) (TIProd IT A' B)
| cp_TIProd_B : forall IT A B B',
    R B B' -> compatible R (TIProd IT A B) (TIProd IT A B')
| cp_TIPi_IT : forall IT A D IT',
    R IT IT' -> compatible R (TIPi IT A D) (TIPi IT' A D)
| cp_TIPi_A : forall IT A D A',
    R A A' -> compatible R (TIPi IT A D) (TIPi IT A' D)
| cp_TIPi_D : forall IT A D D',
    R D D' -> compatible R (TIPi IT A D) (TIPi IT A D')
| cp_TISig_IT : forall IT A D IT',
    R IT IT' -> compatible R (TISig IT A D) (TISig IT' A D)
| cp_TISig_A : forall IT A D A',
    R A A' -> compatible R (TISig IT A D) (TISig IT A' D)
| cp_TISig_D : forall IT A D D',
    R D D' -> compatible R (TISig IT A D) (TISig IT A D')
| cp_TIChoice_IT : forall IT E D IT',
    R IT IT' -> compatible R (TIChoice IT E D) (TIChoice IT' E D)
| cp_TIChoice_E : forall IT E D E',
    R E E' -> compatible R (TIChoice IT E D) (TIChoice IT E' D)
| cp_TIChoice_D : forall IT E D D',
    R D D' -> compatible R (TIChoice IT E D) (TIChoice IT E D')
| cp_TInterp_IT : forall IT D X IT',
    R IT IT' -> compatible R (TInterp IT D X) (TInterp IT' D X)
| cp_TInterp_D : forall IT D X D',
    R D D' -> compatible R (TInterp IT D X) (TInterp IT D' X)
| cp_TInterp_X : forall IT D X X',
    R X X' -> compatible R (TInterp IT D X) (TInterp IT D X')
| cp_TMuI_IT : forall IT D IT',
    R IT IT' -> compatible R (TMuI IT D) (TMuI IT' D)
| cp_TMuI_D : forall IT D D',
    R D D' -> compatible R (TMuI IT D) (TMuI IT D')
| cp_TInMu_IT : forall IT D i x IT',
    R IT IT' -> compatible R (TInMu IT D i x) (TInMu IT' D i x)
| cp_TInMu_D : forall IT D i x D',
    R D D' -> compatible R (TInMu IT D i x) (TInMu IT D' i x)
| cp_TInMu_i : forall IT D i x i',
    R i i' -> compatible R (TInMu IT D i x) (TInMu IT D i' x)
| cp_TInMu_x : forall IT D i x x',
    R x x' -> compatible R (TInMu IT D i x) (TInMu IT D i x')
| cp_TInClose_IT : forall IT F G i x IT',
    R IT IT' -> compatible R (TInClose IT F G i x) (TInClose IT' F G i x)
| cp_TInClose_F : forall IT F G i x F',
    R F F' -> compatible R (TInClose IT F G i x) (TInClose IT F' G i x)
| cp_TInClose_G : forall IT F G i x G',
    R G G' -> compatible R (TInClose IT F G i x) (TInClose IT F G' i x)
| cp_TInClose_i : forall IT F G i x i',
    R i i' -> compatible R (TInClose IT F G i x) (TInClose IT F G i' x)
| cp_TInClose_x : forall IT F G i x x',
    R x x' -> compatible R (TInClose IT F G i x) (TInClose IT F G i x')
| cp_TInd_IT : forall IT D P s i x IT',
    R IT IT' -> compatible R (TInd IT D P s i x) (TInd IT' D P s i x)
| cp_TInd_D : forall IT D P s i x D',
    R D D' -> compatible R (TInd IT D P s i x) (TInd IT D' P s i x)
| cp_TInd_P : forall IT D P s i x P',
    R P P' -> compatible R (TInd IT D P s i x) (TInd IT D P' s i x)
| cp_TInd_s : forall IT D P s i x s',
    R s s' -> compatible R (TInd IT D P s i x) (TInd IT D P s' i x)
| cp_TInd_i : forall IT D P s i x i',
    R i i' -> compatible R (TInd IT D P s i x) (TInd IT D P s i' x)
| cp_TInd_x : forall IT D P s i x x',
    R x x' -> compatible R (TInd IT D P s i x) (TInd IT D P s i x')
| cp_TIAll_IT : forall IT D X x P IT',
    R IT IT' -> compatible R (TIAll IT D X x P) (TIAll IT' D X x P)
| cp_TIAll_D : forall IT D X x P D',
    R D D' -> compatible R (TIAll IT D X x P) (TIAll IT D' X x P)
| cp_TIAll_X : forall IT D X x P X',
    R X X' -> compatible R (TIAll IT D X x P) (TIAll IT D X' x P)
| cp_TIAll_x : forall IT D X x P x',
    R x x' -> compatible R (TIAll IT D X x P) (TIAll IT D X x' P)
| cp_TIAll_P : forall IT D X x P P',
    R P P' -> compatible R (TIAll IT D X x P) (TIAll IT D X x P')
| cp_THyps_IT : forall IT D X P h x IT',
    R IT IT' -> compatible R (THyps IT D X P h x) (THyps IT' D X P h x)
| cp_THyps_D : forall IT D X P h x D',
    R D D' -> compatible R (THyps IT D X P h x) (THyps IT D' X P h x)
| cp_THyps_X : forall IT D X P h x X',
    R X X' -> compatible R (THyps IT D X P h x) (THyps IT D X' P h x)
| cp_THyps_P : forall IT D X P h x P',
    R P P' -> compatible R (THyps IT D X P h x) (THyps IT D X P' h x)
| cp_THyps_h : forall IT D X P h x h',
    R h h' -> compatible R (THyps IT D X P h x) (THyps IT D X P h' x)
| cp_THyps_x : forall IT D X P h x x',
    R x x' -> compatible R (THyps IT D X P h x) (THyps IT D X P h x')
| cp_TClose_IT : forall IT F G IT',
    R IT IT' -> compatible R (TClose IT F G) (TClose IT' F G)
| cp_TClose_F : forall IT F G F',
    R F F' -> compatible R (TClose IT F G) (TClose IT F' G)
| cp_TClose_G : forall IT F G G',
    R G G' -> compatible R (TClose IT F G) (TClose IT F G')
| cp_TCloseCase_IT : forall k IT F G i Q b x IT',
    R IT IT' -> compatible R (TCloseCase k IT F G i Q b x) (TCloseCase k IT' F G i Q b x)
| cp_TCloseCase_F : forall k IT F G i Q b x F',
    R F F' -> compatible R (TCloseCase k IT F G i Q b x) (TCloseCase k IT F' G i Q b x)
| cp_TCloseCase_G : forall k IT F G i Q b x G',
    R G G' -> compatible R (TCloseCase k IT F G i Q b x) (TCloseCase k IT F G' i Q b x)
| cp_TCloseCase_i : forall k IT F G i Q b x i',
    R i i' -> compatible R (TCloseCase k IT F G i Q b x) (TCloseCase k IT F G i' Q b x)
| cp_TCloseCase_Q : forall k IT F G i Q b x Q',
    R Q Q' -> compatible R (TCloseCase k IT F G i Q b x) (TCloseCase k IT F G i Q' b x)
| cp_TCloseCase_b : forall k IT F G i Q b x b',
    R b b' -> compatible R (TCloseCase k IT F G i Q b x) (TCloseCase k IT F G i Q b' x)
| cp_TCloseCase_x : forall k IT F G i Q b x x',
    R x x' -> compatible R (TCloseCase k IT F G i Q b x) (TCloseCase k IT F G i Q b x')
| cp_TCloseInd_IT : forall IT G P s F i x IT',
    R IT IT' -> compatible R (TCloseInd IT G P s F i x) (TCloseInd IT' G P s F i x)
| cp_TCloseInd_G : forall IT G P s F i x G',
    R G G' -> compatible R (TCloseInd IT G P s F i x) (TCloseInd IT G' P s F i x)
| cp_TCloseInd_P : forall IT G P s F i x P',
    R P P' -> compatible R (TCloseInd IT G P s F i x) (TCloseInd IT G P' s F i x)
| cp_TCloseInd_s : forall IT G P s F i x s',
    R s s' -> compatible R (TCloseInd IT G P s F i x) (TCloseInd IT G P s' F i x)
| cp_TCloseInd_F : forall IT G P s F i x F',
    R F F' -> compatible R (TCloseInd IT G P s F i x) (TCloseInd IT G P s F' i x)
| cp_TCloseInd_i : forall IT G P s F i x i',
    R i i' -> compatible R (TCloseInd IT G P s F i x) (TCloseInd IT G P s F i' x)
| cp_TCloseInd_x : forall IT G P s F i x x',
    R x x' -> compatible R (TCloseInd IT G P s F i x) (TCloseInd IT G P s F i x').
