"""Generate repetitive annotated syntax, binding operations, and erasure.

Run from any directory with Python 3. Proofs live in separate .v files.
Each term field records its binder depth and whether erasure retains it.
"""
from pathlib import Path


def term(name, depth=0, retained=True):
    return name, "term", depth, retained


def number(name):
    return name, "nat", 0, True


# A/B on eliminations record the dependent input type. The B field binds
# one variable just as the codomain of a Pi/Sigma does. Lambda B and b
# both bind the argument; its domain A does not.
SCHEMA = [
    ("TVar", [number("n")]),
    ("TSort", [number("k")]),
    ("TPi", [term("A"), term("B", 1)]),
    ("TLam", [term("A", retained=False), term("B", 1, False), term("b", 1)]),
    ("TApp", [term("A", retained=False), term("B", 1, False), term("f"), term("a")]),
    ("TSigma", [term("A"), term("B", 1)]),
    ("TPair", [term("A", retained=False), term("B", 1, False), term("a"), term("b")]),
    ("TFst", [term("A", retained=False), term("B", 1, False), term("p")]),
    ("TSnd", [term("A", retained=False), term("B", 1, False), term("p")]),
    ("TUnitT", []), ("TUnit", []), ("TUId", []),
    ("TTag", [("s", "string", 0, True)]),
    ("TEnumU", []), ("TNilE", []),
    ("TConsE", [term("tag"), term("E")]),
    ("TEnumT", [term("E")]),
    ("TEZero", [term("tag", retained=False), term("E", retained=False)]),
    ("TESucc", [term("tag", retained=False), term("E", retained=False), term("n")]),
    ("TEPi", [number("k"), term("E"), term("P")]),
    ("TSwitch", [number("k"), term("E"), term("P"), term("p"), term("e")]),
    ("TIDesc", [term("IT")]),
    ("TIVar", [term("IT", retained=False), term("i")]),
    ("TI1", [term("IT", retained=False)]),
    ("TIBot", [term("IT", retained=False)]),
    ("TIProd", [term("IT", retained=False), term("A"), term("B")]),
    ("TIPi", [term("IT", retained=False), term("A"), term("D")]),
    ("TISig", [term("IT", retained=False), term("A"), term("D")]),
    ("TIChoice", [term("IT", retained=False), term("E"), term("D")]),
    ("TInterp", [term("IT"), term("D"), term("X")]),
    ("TMuI", [term("IT"), term("D")]),
    ("TInMu", [term("IT", retained=False), term("D", retained=False),
               term("i", retained=False), term("x")]),
    ("TInClose", [term("IT", retained=False), term("F", retained=False),
                  term("G", retained=False), term("i", retained=False), term("x")]),
    ("TInd", [term(n) for n in ["IT", "D", "P", "s", "i", "x"]]),
    ("TIAll", [term(n) for n in ["IT", "D", "X", "x", "P"]]),
    ("THyps", [term(n) for n in ["IT", "D", "X", "P", "h", "x"]]),
    ("TClose", [term(n) for n in ["IT", "F", "G"]]),
    ("TCloseCase", [number("k")] + [term(n) for n in ["IT", "F", "G", "i", "Q", "b", "x"]]),
    ("TCloseInd", [term(n) for n in ["IT", "G", "P", "s", "F", "i", "x"]]),
]


def applied(name, args):
    return " ".join([name, *args])


def cutoff(depth):
    return "(S c)" if depth else "c"


def generate():
    lines = [
        "(* Annotated open-signature core, under construction.",
        "   Generated by annotated/generate_syntax.py; proofs are separate.",
        "   All hidden introduction/elimination types are retained as terms.",
        "   Binding and eta freshness include these annotations. *)",
        "From Stdlib Require Import List Arith String.",
        "Import ListNotations.",
        "",
        "Inductive term : Type :=",
    ]
    for name, fields in SCHEMA:
        args = [f"({n} : {ty})" for n, ty, _, _ in fields]
        lines.append("| " + applied(name, args))
    lines[-1] += "."
    for op, signature in [
        ("lift", "(d c : nat) (t : term) : term"),
        ("subst", "(u : term) (c : nat) (t : term) : term"),
        ("occurs", "(c : nat) (t : term) : bool"),
        ("tsize", "(t : term) : nat"),
    ]:
        lines += ["", f"Fixpoint {op} {signature} :=", "  match t with"]
        for name, fields in SCHEMA:
            lhs = applied(name, [n for n, _, _, _ in fields])
            if name == "TVar" and op != "tsize":
                rhs = {
                    "lift": "if n <? c then TVar n else TVar (d + n)",
                    "subst": "if n <? c then TVar n else if n =? c then lift c 0 u else TVar (Nat.pred n)",
                    "occurs": "n =? c",
                }[op]
            elif op == "occurs":
                args = [f"occurs {cutoff(dep)} {n}" for n, ty, dep, _ in fields if ty == "term"]
                rhs = " || ".join(args) if args else "false"
            elif op == "tsize":
                args = [f"tsize {n}" for n, ty, _, _ in fields if ty == "term"]
                rhs = "S (" + " + ".join(args) + ")" if args else "1"
            else:
                first = "d" if op == "lift" else "u"
                args = [f"({op} {first} {cutoff(dep)} {n})" if ty == "term" else n
                        for n, ty, dep, _ in fields]
                rhs = applied(name, args)
            lines.append(f"  | {lhs} => {rhs}")
        lines.append("  end.")
    lines += [
        "", "Definition ctx := list term.",
        "Definition arrow A B := TPi A (lift 1 0 B).",
        "Definition product A B := TSigma A (lift 1 0 B).",
        "Definition Def IT := TPi IT (TIDesc (lift 1 0 IT)).",
        "Definition Family IT := TPi IT (TSort 0).",
        "Definition Bot := TEnumT TNilE.",
    ]
    # A one-hole compatible context includes every annotation. The generated
    # constructors are useful both for reduction and annotation normalization.
    lines += ["", "Inductive compatible (R : term -> term -> Prop) : term -> term -> Prop :="]
    for name, fields in SCHEMA:
        for changed, ty, _, _ in fields:
            if ty != "term":
                continue
            names = [n for n, _, _, _ in fields]
            lhs = applied(name, names)
            rhs = applied(name, [n + "'" if n == changed else n for n in names])
            lines.append(f"| cp_{name}_{changed} : forall {' '.join(names)} {changed}',")
            lines.append(f"    R {changed} {changed}' -> compatible R ({lhs}) ({rhs})")
    lines[-1] += "."
    destination = Path(__file__).resolve().parent
    (destination / "ASyntax.v").write_text("\n".join(lines) + "\n")
    lines = [
        "(* Annotation erasure; generated by annotated/generate_syntax.py. *)",
        "Require Export annotated.ASyntax.",
        "Require nameless.DBSyntax.",
        "Module Raw := nameless.DBSyntax.",
        "", "Fixpoint erase (t : term) : Raw.term :=", "  match t with",
    ]
    for name, fields in SCHEMA:
        lhs = applied(name, [n for n, _, _, _ in fields])
        raw_name = "TIn" if name in {"TInMu", "TInClose"} else name
        rhs = applied("Raw." + raw_name, [f"(erase {n})" if ty == "term" else n
                                      for n, ty, _, retained in fields if retained])
        lines.append(f"  | {lhs} => {rhs}")
    lines += ["  end.", ""]
    (destination / "AErase.v").write_text("\n".join(lines))


if __name__ == "__main__":
    generate()
